### ISSUE TITLE
Ordered lists always use "1."

### ISSUE THREAD

**Issue by rohand-cerebras** [catcombo/jira2markdown#24]
Why do all elements in an ordered list start with "1." instead of incrementing? This is not how they show up in Jira.

<table>
<tr>
<th>Jira</th>
<th>Markdown</th>
</tr>

<tr>
<td>

```
# a
# numbered
# list
```
</td>
<td>

```
1. a
1. numbered
1. list
```
</td>
</tr>
</table>

**Comment by catcombo** [comment]
Hi @rohand-cerebras!

It was made like this because markdown renderers handle list numbers correctly, even if they are the same. You can check it in the GitHub comments:

1. a
1. numbered
1. list

HTML renderers (e.g. https://github.com/Python-Markdown/markdown) handle this correctly as well:
```python
import markdown

print(
    markdown.markdown("""
1. a
1. numbered
1. list
    """)
)
# <ol>
# <li>a</li>
# <li>numbered</li>
# <li>list</li>
# </ol>
```

Such approach also simplifies the code, because I don't need to track list item numbers.
